overextended/ox_lib

resource/streaming/client.lua

This is a bit of a mess since I've had it sitting around for about a month and I don't know how to split it up nicely at this point.
It's basically 2 parts:
- adds the timeout parameter 
allows the number of ticks before timeout to be specified, timeout is avoided if `nil`
20 ticks was rarely enough for vehicle spawns
- returns the requested item on success
basically just to return the vehicle hash so I don't have to `joaat` it twice
added to the other functions for consistency
I haven't tested the functions aside from `requestAnimDict` and `requestModel` but everything should still function

feat(resource/streaming): set timeout length and return requested item on success

---

resource/interface/client/context.lua
web/src/features/menu/Item.tsx

Fixes a security flaw, where players can use nui_devtools to trigger any server / client event.

feat(context): prevent event triggering

---

init.lua
resource/interface/client/progress.lua
web/src/features/progress/CircleProgressbar.tsx

Allows the option for text/label under the circular progress bar

feat(circleprogress): Add Labels

---

web/src/features/dialog/InputDialog.tsx
web/src/features/dialog/components/checkbox.tsx
web/src/features/dialog/components/input.tsx
web/src/features/dialog/components/number.tsx
web/src/features/dialog/components/select.tsx
web/src/interfaces/dialog.ts

- Placeholders for input and number type
- Default values for input, number and checkbox type

feat(web/dialog): Support default values

---

resource/interface/client/menu.lua
web/src/features/dialog/components/select.tsx

React doesn't like the `selected` attribute (causing a warning in web console - not in-game).
`defaultValue` should be used instead so there is no need to create placeholder option if `defaultValue` is already defined by row options.

fix(web/dialog): Setting non-selectable placeholder

---

resource/interface/client/menu.lua
web/src/features/dialog/InputDialog.tsx
web/src/features/dialog/components/checkbox.tsx
web/src/features/dialog/components/input.tsx
web/src/features/dialog/components/number.tsx
web/src/features/dialog/components/select.tsx
web/src/interfaces/dialog.ts

For better typing of row options for different input types.
Eg. various components accepts different value types for `defaultValue`, so it should be split for each input type.

refactor(web/dialog): Split interfaces

---

web/src/features/notifications/NotificationWrapper.tsx

* `id` was being checked for but never got set on the toast so you'd continue to get duplicate messages even if `id` was set

fix(notification): Notification id now works as documentation states

---

resource/interface/client/menu.lua

openMenu gets defined nil even when the options has passed close = false which result in error

Fix openMenu gets defined nil

---

package/client/resource/interface/menu.ts
resource/interface/client/menu.lua
web/src/features/menu/list/index.tsx

keyPressed for onClose

---

web/src/features/menu/list/index.tsx

This fixes the issue of canClose stopping the menu from being closed when using lib.hideMenu

fix(web/features/menu/list): force close menu when using the nui event

---

imports/keybinds/client.lua

This adds a management interface for keymaps to allow you to disable, enable and control them in a centralized manner.
Usage:
```lua
local function handsupFuncPress()
-- triggered when the button is pressed
end
local function handsupFuncRelease()
-- triggered when the button is released
end
local handsup = lib.keybinds.new({
name = 'handsup', -- name has to be unique (the case for commands stuff)
keybind = 'X',
description = 'Put Your Hands Up',
onPressed = handsupFuncPress,
onReleased = handsupFuncRelease,
})
local function anotherFunc()
-- doing something here, disable handsup keybind
handsup:disable(true)
-- another statement, re enable handsup keybind
handsup:disable(false)
end
-- Another script
local handsup = lib.keybinds.get('handsup')
-- print(handsup.disabled) prints true or …
```

feat(keybinds): add keymap manager

---

package/client/resource/interface/textui.ts
resource/interface/client/textui.lua

Since the text ui can be overwritten using lib.showTextUI or hidden when it shouldn't, we should be able to check whether the textui is already open or not to prevent it

open state getter for textUI

---

imports/logger/server.lua

Only Loki logging was affected. When no tags were given and the source is console the `convertDDTagsToKVP` break because of the nil value.
```
[ script:ox_inventory] SCRIPT ERROR: @ox_lib/logger/server.lua:103: bad argument #2 to 'strsplit' (string expected, got nil)
```

fix(logger): Fix bad argument #2 to strsplit

---

imports/logger/server.lua

Fixes an error caused when passing no (or nil) extra parameters. Seems to originate from #125

fix(logger/loki): Fix error when passing invalid/nil tags

---

package/client/resource/interface/input.ts
resource/interface/client/input.lua
web/src/features/dialog/components/input.tsx
web/src/features/dialog/components/number.tsx
web/src/features/dialog/components/select.tsx
web/src/features/dialog/components/slider.tsx
web/src/interfaces/dialog.ts

This adds support for making fields disabled or read only.

feat(interface/dialog): readonly, disabled flags

---

web/src/features/menu/list/index.tsx

* This fixes a case where, if the first option selected in a menu doesn't have side scroll values, the first time that you *did* side scroll on an item in that menu it would not trigger onSideScroll

fix(web/menu/list): Move firstRenderRef check earlier in the function

---

package/client/resource/interface/menu.ts
resource/interface/client/menu.lua
web/src/features/dev/debug/menu.ts
web/src/features/menu/list/CustomCheckbox.tsx
web/src/features/menu/list/ListItem.tsx
web/src/features/menu/list/index.tsx

It works, but the style is not good, so I'll let frontend-god Luke finish this

feat(menu): checkbox

---

web/src/features/dev/debug/context.ts
web/src/features/dev/debug/menu.ts
web/src/features/menu/context/Item.tsx
web/src/features/menu/list/ListItem.tsx
web/src/features/menu/list/index.tsx
web/src/interfaces/context.ts

Adds support for progress bars to items in both context and list menus. 
-  `progress` key in the option. It will be a number between 0 and 100 (inclusive) as a percentage.
-  `colorScheme` key in the option for the progress bar. Defaults to gray.
- `iconColor` added to menu

[Menu] Progress Bars

---

web/src/features/menu/list/index.tsx

* Combining these checks should fix an issue of having to toggle a checkbox multiple times before it is recognized as being toggled

fix(web/menu): Combine initial select and first render checks

---

imports/requestScaleformMovie/client.lua

Some scaleform related natives requires the scaleform handle - eg. `BeginScaleformMovieMethod`.

fix(imports/scaleform): return scaleform handle

---

resource/zoneCreator/client.lua

Both of these are features from PolyZone that I found myself missing when we switched over to using GLM. 
saving a zone saves some of its data to the lastZone variable. If the lastzone command is run, it then uses these values instead of the defaults to keep the same shape as the last zone created. This only works for box and sphere zones
for relative movement I did some small edits to the Polyzone.rotate function from PolyZone to make it fit and used that to determine the new position based on the camera rotation. I.e. when you press 'w', the zone will move in what ever direction the camera is facing, a will move it to the left of that direction, etc.

lastzone command and relative movement for zone creator

---

package/client/resource/interface/alert.ts
resource/interface/client/alert.lua
web/src/features/dev/debug/alert.ts
web/src/features/dialog/AlertDialog.tsx

In regards to this suggestion: #178
Added:
- size prop
- overflow prop
Updated:
- npm package types to reflect the newly added ones
- lua types to also reflect the newly added ones 
seem that the centered prop is already added as an option to the alert dialog.

feat(web/alert): new options for alert dialog

---

web/package.json
web/pnpm-lock.yaml
web/vite.config.ts

Updated vite to v4 and updated the react-plugin to support the v4 changes. Made sure dev port was staying consistent and manually set it to `:3000`

chore(web): migrate to vite v4

---

resource/interface/client/progress.lua

Changes:
- Stops setting the data.anim to a boolean value because we aren't using the same if statement for cancelling the tasks
- If animation then it will cancel only the animation played by the progress bar
- If scenario then it will clear ped tasks like before
This should make it so people can do things like eat sitting down and after a progress bar animation it won't make you stand up.

fix/feat(progressbar): Better animation cancelling

---

web/src/features/dev/debug/context.ts
web/src/features/menu/context/components/ContextButton.tsx
web/src/interfaces/context.ts

On each metadata item you can set progressbar also you can still set value (not required) like this;
```
{
["label"]: "Body",
["value"]: "55%",
["progress"]: 55
}
```
or just like this;
```
{
["label"]: "Oil",
["progress"]: 11
}
```

feature: progress bar in context menu's metadata

---

package/client/resource/interface/context.ts
package/client/resource/interface/menu.ts
web/src/features/menu/context/components/ContextButton.tsx
web/src/features/menu/list/ListItem.tsx
web/src/typings/context.ts
web/src/typings/menu.ts
web/src/utils/isIconUrl.ts

in my server. ox_lib is heavily used.
most of sample use cases for this is.
Food image,
Ingredients,
Vehicle Parts,
etc..
i believe font awesome is not enough for some use cases.
i did suggest this on v3 pending PR.
but it seems gets ignored.
here i am gonna try to push this PR.
to use this.
icon must be not existing in the options.
if both icon and image is in options, nothing will appear.
image in metadata will still appear normaly.
Sample:
sample usage:
```
image = 'nui://ox_inventory/web/images/engine.png',
```

feat: Support image Tag in buttons

---

resource/interface/client/radial.lua
web/src/features/menu/radial/index.tsx
web/src/typings/radial.ts

Fixes https://github.com/overextended/ox_lib/issues/242
Since items lack an id, I'm storing the item label on `menuHistory` alongside the id. Also added the global radial menu to the `menuHistory` with id = nil.
added an option label parameter to `showRadial`  that gets passed to the NUI and used to find the page where that item will be

fix(radial): go back to correct more page when going back from sub

---

resource/interface/client/radial.lua

Fixes https://github.com/overextended/ox_lib/issues/254
Since global radial is an array of items, `addRadialItem` appends to the end of the array even if a radial item with the same id already exists.

fix(radial): Replace global item with same id instead of duplicating

---

resource/version/server.lua
resource/version/shared.lua

Match major versions (`X.y.z`) with multiple digits.
Previously versions like `10.0.0` would get matched as `0.0.0` and the rest of the major version would be ignored.
I haven't actually tested this in a server but the issue seems pretty clear and easy to fix.

fix(version): match major versions with multiple digits

---

resource/interface/client/context.lua
resource/interface/client/input.lua
resource/interface/client/main.lua
resource/interface/client/menu.lua
resource/interface/client/notify.lua
resource/interface/client/radial.lua
resource/interface/client/textui.lua

`['far', 'heart']` is also a valid icon prop
I swear I read this on the docs, maybe on v2?
I can also update the docs if this gets merged

fix(interface): Add table<string, string> to icon typings

---

resource/interface/client/radial.lua

I used this for our conversion from qb-radialmenu to clear the menu then only add a "call for help" option or similar. Figured it could be useful in other niche situations

Add clearAllRadialItems

---

web/src/features/menu/radial/index.tsx

Previously, menu pages with 8 buttons/slices would move the 8th button to the next page and replace it with a `More...` button.
This PR changes the functionality so that a `More...` button is added only if there are *more* than 8 buttons in the current page.

feat(interface/radial): don't show more button in pages with 8 slices

---

imports/addKeybind/client.lua

Usefull to be able to register other inputs such as `MOUSE_BUTTON`
Will break current people stuff tho

feat(addKeybind): support others defaultMapper

---

imports/requestWeaponAsset/client.lua
package/client/resource/streaming/index.ts

Adds [RequestWeaponAsset](https://docs.fivem.net/natives/?_0x5443438F033E29C3) to the lib.
Added p1 as 31 and p2 as 0 for the lua version.
Regarding the npm package I used the generic function so p1 and p2 weren't included but was able to use [CreateWeaponObject](https://docs.fivem.net/natives/?_0x9541D3CF0D398F36) and [ShootSingleBulletBetweenCoords](https://docs.fivem.net/natives/?_0x867654CBC7606F2C) without issues when testing.

feat(streaming): RequestWeaponAsset

---

resource/interface/client/radial.lua

Radialmenu ran into a issue with keep closing when onReleased = lib.hideRadial was uncommented.
Looking back at the commit history this used to be set to true aswel not sure why that was changed but this fixed onReleased issue.

fix(interface/radial): SetNuiFocusKeepInput to true

---

imports/logger/server.lua

This is helpful for simple environments which don't have SSL enabled
- Defaults to `https`

feat(logger/loki): Allow users to specify protocol for requests

---

imports/logger/server.lua

- Renamed `service` and `hostname` to `resource` and `event` 
- Added  `server` label that corresponds to `sv_projectName` which is useful for distinguishing between logs coming from different servers

fix(logger/loki): Consistent stream labels

---

resource/interface/client/context.lua

After a recent update from @thelindat NUI focus was not reset, meaning that the user would get stuck, when trying to access a third party UI such as inventory.
Yes obviously I know u cant open the drop like this but Still got me stuck, and this PR seems to fix it did some testing with opening multiple context menus to make sure I didnt mess up somewhere and it seems to work as intended now
```lua
RegisterCommand('testshit', function()
lib.registerContext({
id = 'dadlover69420',
title = 'Test inventory stuff',
position = 'top-right',
options = {
{
title = "teststuff",
arrow = true,
icon = 'turn-up',
onSelect = function()
ox_inventory:openInventory('drop', '')
end,
},
}
})
lib.showContext("dadlover69420")
end, false)
```

Fix(context): ResetNUI Focus

---

imports/math/shared.lua

thought it'd be a good idea to include this in math lib

update(math): group digits

---

imports/cron/server.lua

This allows `getNextTime` to return an absolute next time (ignoring if it's today or not) to be returned. Can be useful in some scenarios.

tweak(server/cron): getNextTime param to return time for any day

---

imports/cron/server.lua

Some issues this is focused on:
- getAbsoluteNextTime used to add a year to next time in some edge cases
- getAbsoluteNextTime used to calculate very wrong time if task was scheduled for first or last day of the month
- getNextTime used to return nil if task was scheduled for last day of the month and currentDate is that day
More things to be concerned about:
- did not check the edge cases for months and weekdays
- getTimeUnit returns 0 if task is scheduled for last day of the month and currentDate is that day
- some testing env for custom currentDate could be useful? (would be interested what kind of implementation of this would be acceptable, I'd happily do that)

Cron edge cases fixes

---

web/src/features/dialog/components/fields/number.tsx

Now if someone enters a number that is lower or higher than allowed and presses enter instead of the send button, it will send unclamped number.

fix(web/input): Blocks form submission with unclamped numbers

---

imports/logger/server.lua

Remove the text formatting codes commonly used in server names when setting the hostname to be used in the logger.

tweak(server/logger) remove text formatting from hostname

---

resource/vehicleProperties/client.lua

In some cases setting predefined colour doesn't override custom colour, so it requires to clear it out additionaly.

bugfix: force clear vehicle custom colors before applying colours

---

web/src/features/dev/debug/input.ts
web/src/features/dialog/components/fields/checkbox.tsx
web/src/features/dialog/components/fields/number.tsx
web/src/typings/dialog.ts

- fix: added missing disabled prop to checkbox
- checkbox disabled prop used to not work
- feat: added precision prop for number input
- without this, the number from input was always returned as integer, while in some cases float might be useful

Changes to input fields

---

resource/vehicleProperties/client.lua

Fixed incorrect usage of the `ClearVehicleCustomPrimaryColour()` function on the secondary color.
Added new properties
- paint1 
- paint2 
These 2 functions (get and set) were missing custom paint properties.
The following FiveM natives only work if there is a "RGB coating" applied to the vehicle
```lua
SetVehicleModColor_1()
SetVehicleModColor_2()
```
This "coating" I am referring to is applied when using 
```lua
SetVehicleCustomPrimaryColour()
SetVehicleCustomSecondaryColour()
```
and they can be removed by using
```lua
ClearVehicleCustomPrimaryColour()
ClearVehicleCustomSecondaryColour()
```
I hope this clarifies some doubts around these messy natives.

Fixing and Adding new properties to the vehicleProperties/client.lua

---

package/client/resource/vehicleProperties/index.ts
resource/vehicleProperties/client.lua

When using SetVehicleAutoRepairDisabled, you need to repair the vehicle for the applied extras to be visible.

fix(client/vehicleproperties): vehicle must be fixed for extras to apply visually

---

package/client/resource/interface/input.ts
resource/interface/client/input.lua
web/src/features/dialog/InputDialog.tsx
web/src/features/dialog/components/fields/date.tsx
web/src/typings/dialog.ts

returnString allows for a date to be returned as a string following the format if it is defined, otherwise returns to a default format.

Add returnString field to date and date-range type in input

---

resource/vehicleProperties/client.lua

The native GetDriftTyresEnabled throws an error when used on gamebuilds below 2372 which makes lib.getVehicleProperties unusable.

fix(client/vehicleProperties): Fix error on gamebuilds below 2372

---

imports/print/shared.lua

- added convar 'ox:printlevel'
- can override the global setting on a per-resource basis with 'ox:printlevel:<resourceName>'
- supported levels are debug, info, warn, and error. Considered adding trace and severe, but think that might just be overkill
- Examples:
Client:
Server: Unfortunately duplicating the resource name seems necessary so that when chat forwards the print, the client can see the original resource.
Server forwarded print to client through Chat resource:

feat: added lib.print to print different log levels to console

---

imports/math/shared.lua

this small addition allows developers to pass in a surface normal and get a rotation vector in return. this function has been useful in object placement, spray paints, decals, etc. 
docs are done as well [here](https://github.com/overextended/overextended.github.io/pull/156)
```lua
RegisterCommand("testnormalrot", function()
lib.requestModel(`prop_mp_cone_01`)
local playerCoords = GetEntityCoords(cache.ped)
local object = CreateObject(`prop_mp_cone_01`, playerCoords.x, playerCoords.y, playerCoords.z, false, false, false)
SetEntityAlpha(object, 200)
SetEntityRotation(object, rot.x, rot.y, rot.z, 1)
DisableCamCollisionForEntity(object)
SetEntityCollision(object, false, false)
SetEntityDrawOutlineColor(10, 170, 210, 200)
SetEntityDrawOutlineShader(0)
SetEntityDrawOutline(object, true)
while …
```

Normal to rotation

---

imports/require/shared.lua

Currently if any part of the script is escrowed (tested on a couple of scripts) the resourceSrc would return ?
This is really the definition of a plaster solution feel free to close if you have a better way of doing this thanks.

fix(require): plaster solution for escrowed scripts

---

resource/interface/client/progress.lua

Adds feature to disable sprinting only, instead of all movements.

feat(progress): disable sprinting only

---

imports/logger/server.lua

For environments running Loki in multi_tenant mode, it is required to provide an explicit tenant to where the logs should go in Loki. The "Tenant" feature allows for data abstraction at a "DS (Datasource)" level in Grafana. 
This PR just adds the required headers to allow for those Loki clusters to ingest the logs.
Reference documentation that explains why / when its needed: https://grafana.com/docs/loki/latest/operations/authentication/#authentication
I'l also create follow-up PR to the docs which adds the convar

feat(logger/loki): Support for tenants when running Loki in multi-tenant mode

---

package/server/resource/addCommand/index.ts
package/server/resource/index.ts

I would like to mention in advance that I am completely new to TS and thanks to the transition of ox_core to TS I got the motivation to dive more into this and learn the language.
I looked at what is available in ox_lib for TS and addCommand came to me as one of the few must have functions that ox_lib currently lacks..
I am more than sure that this PR has flaws and I would appreciate any feedback and change requests
Tested with:
```
import { addCommand } from '@overextended/ox_lib/server'
addCommand('tscommand', (source: number, args: any, raw: string) => {
console.log(`player ${source} executed comand (${raw})`)
}, {help: 'TypeScript addCommand', params: [{name: 'target', paramType: 'playerId', help: 'playerId or "me"', optional: true}], restricted: ['group.typescript', …
```

TS support for addCommand

---

imports/require/shared.lua

`true` should be the fallback value when the code chunk returns `nil`, but that should not be the case when it returns `false`.

fix(imports/require): return `false` when the code chunk returns `false`

---

package/client/resource/interface/radial.ts
resource/interface/client/radial.lua
web/src/features/dev/debug/radial.ts
web/src/features/menu/radial/index.tsx
web/src/typings/radial.ts

I like the radial menu.
I use it in one of my projects, and it lack the option to use non FA icons.
This PR is an example implementation to add support for this.
I added width and height parameters to adapt to the images. 
I also fixed the type in debug/radial.ts.
Documentation update can be found here : #https://github.com/overextended/overextended.github.io/pull/169

feat(package): support icon urls in radial menu

---

imports/require/shared.lua

This PR addresses the issue where the resource source extraction in the `getModuleInfo` function was not working as expected due to the `short_src` field being truncated when the calling Lua file is located inside a folder with a long path. This led to errors when calling `LoadResourceFile`.
- Updated the `getModuleInfo` function in `ox_lib/imports/require/shared.lua` to use the `source` field instead of `short_src` when extracting the resource source.
- Modified the regex pattern to properly capture the resource source from the `source` field, ensuring compatibility with long file paths.
- `short_src` doesn't match `source` on the call stack when calling require inside a lua file with a long nested path, which was causing the regex to not work as expected.
- The issue was due to the Lua …

fix(imports/require): Fix resource source extraction in `getModuleInfo`

---

package/client/resource/interface/input.ts
resource/interface/client/input.lua
web/src/features/dialog/components/fields/select.tsx
web/src/typings/dialog.ts

As title mentions, this PR just adds the possibility to set the searchable prop to the 'select' and 'multi-select' input dialogs.
It's just an already existing feature in Mantine that is very helpful when the options list is too large.

Added searchable prop to select and multi-select input types

---

resource/interface/client/progress.lua

add allowSwimming to allow the progress bar to continue while swimming, or cancel if set to false/nil(default value)

add allowSwimming field to Progress

---

imports/requestAudioBank/client.lua
resource/interface/client/notify.lua

As requested by luke, #362 and #441. Adds support for an additional table value to be passed in to play sounds 
Example:
```lua
lib.notify({
title = 'Info', 
description = 'my text.',
position = 'top',
duration = 5000, 
sound = {--[[bank = "BANKNAME",]] name = "Near_Miss_Counter_Reset", set = "GTAO_FM_Events_Soundset"}, 
type = 'success'
})
```

feat(client/notification): add support for native audio sounds

---

imports/logger/server.lua

Proposal to add Fivemanage as a logging option to ox_lib logger import.
Didn't want to start modifying the parameters for the function, but if you want to, we can also alter it to instead just accept key/value data and level. Right now, everything is just "info".
Up to you guys to decide.

feat(imports/logger): add fivemanage as logging option

---

locales/no.json

Update the Norwegian translation file to include the txadmin locales and the new translatable keymapping descriptions.
It's worth noting that the translation for `cancel_progress` could be improved upon, as I could not find or figure out a good translation for "progressbar".

chore(locale): update no.json

---

imports/requestScaleformMovie/client.lua

`HasScaleformMovieLoaded` requires scaleform handle, not scaleform name.
Because of that, the generic `lib.streamingRequest` can't be used.

fix(requestScaleformMovie): use scaleform handle

---

package/client/resource/interface/notify.ts
resource/interface/client/notify.lua
web/package.json
web/pnpm-lock.yaml
web/src/features/dev/debug/notification.ts
web/src/features/notifications/NotificationWrapper.tsx
web/src/typings/notifications.ts

**lib.notify New Option**
```typescript
showDuration?: boolean -- Option to show duration bar
```
**Example:**
```lua
lib.notify({
title = 'Custom',
description = 'Custom',
showDuration = true,
icon = 'eye',
iconColor = '#C53030'
})
```
**Preview:**

feat(notify): add option to show duration

---

imports/timer/shared.lua

while looking throught the issues for ox_lib i saw that this module was a suggested feature #358 from a while ago. was bored so i decided to create it.
- create both async and sync timers to trigger delayed functions
- pause and play timers after creation
- force timers to end early and optionally trigger the onEnd cb function still
this module aims reduce the amount of reused code for timers in resources as well as provide useful methods, extending the utility of the normal timers youd see:
```lua
-- traditional timer in a resource
local start = GetGameTimer()
local timer = 1000
while GetGameTimer() - start > timer do
Wait(0)
end
-- do something
```
```lua
--sync
print('before')
local timer = lib.timer(5000, function()
print(GetGameTimer() - start)
end)
print('after')
```
```lua
-- async …
```

timer module

---

web/src/features/notifications/NotificationWrapper.tsx

This pull request is a fix for issue #554 
Reset circle animation when re-triggering a notification with `ID`.
Assigning unique keys to each `RingProgress` instance allows React to properly manage its state and trigger re-renders when necessary.

fix(notify): reset circle animation on notification re-trigger with id

---

imports/class/shared.lua

I created issue (#549) about not expecting value from private table. Commit dcdfe6e4421d8016e6e707c0b1a88a1e5d119b76 partially fixed this, but it creates a new issue.
Now, class documentation has one error, actually `jesse.private.year` returns 3, not nill.
```
-- code from https://overextended.dev/ox_lib/Modules/Class/Shared#example
CreateThread(function()
local jesse = Student:new('Jesse', 2)
jesse:introduceSelf() -- Hi! I'm Jesse, and I'm in year 2.
jesse:setYear(3)
jesse:introduceSelf() -- Hi! I'm Jesse, and I'm in year 3.
print(jesse.private.year) -- nil  [now, this returns 3, not nil]
print(getmetatable(jesse.private)) -- private
jesse.private.year = 4 -- error
end)
```
I solve this with this simple if statement, and it works fine:
```
__index = function(self, index)
local di = …
```

fix(class): fixed private access in method calls

---

web/src/features/notifications/NotificationWrapper.tsx

Using `useRef` causes notifications without an `ID` resets or re-renders the circle duration so i changed it back to `useState` to avoid re-rendering. Additionally, I've made some improvements and organized the code.

refactor(web/notify): changed useRef to useState to prevent resetting the circle on notifications without an ID and organized the code.

---

imports/math/shared.lua

`math.lerpVectors` is a standard linear interpolation between 2 vectors. This will allow developers to smoothy transition between 2 vectors for rotations or coords over a set duration.
this function is currently blocking. optional async is something that we can add if desired.
example: 
```lua
RegisterCommand('testLerp', function(source, args, raw)
lib.requestModel(`gr_prop_gr_target_04b`)
local offset = GetOffsetFromEntityInWorldCoords(cache.ped, 0, 3.0, 0)
local object = CreateObject(`gr_prop_gr_target_04b`, offset.x, offset.y, offset.z, false, false, false)
PlaceObjectOnGroundProperly_2(object)
math.lerpVectors(vec3(0, 0, 0), vec3(-90.0, 0, 0), 500, function(interpolated)
SetEntityRotation(object, interpolated.x, interpolated.y, interpolated.z, 0, false)
end)
end)
``` …

linear interpolation for vectors.

---

resource/interface/client/progress.lua

As the rotation order varies wildly across community scripts, and Rockstar usually uses order 2, allowing overrides here is important for compatibility when updating legacy resources.
From a personal perspective, order 0 is kinda just a pain in the ass to use. The X and Z axes have to be manipulated in inverse to each other to produce meaningful rotation. There is also an inversion zone, which causes unexpected shifting at some points of X/Z crossover. Order 1, as well as some others, are much more friendly to work with.

Allow explicit rotation order for Progress props

---

package/client/resource/interface/input.ts
resource/interface/client/input.lua
web/src/features/dialog/components/fields/select.tsx
web/src/typings/dialog.ts

Allows using the max prop to limit how many options can be selected in a multi-select input field. This is an already existing feature in Mantine that I believe could be useful.
A PR has been submitted to update the docs as well in overextended/overextended.github.io#182

feat(interface/multi-select): add max prop

---

resource/interface/client/alert.lua

set the parameter `timeout` as optional in function `lib.alertDialog`.

fix?(interface/alert): set timeout as optional parameter

---

imports/getClosestPlayer/server.lua

The parameter is optional, but not it's type

chore(types): optional param in getClosestPlayer

---

imports/logger/server.lua

Hey!
i dont know if this is expected behaviour and the loki provider probably needs more rework but i played around with it a bit and currently its submitting the data in a wrong format. The code i used to submit logs (test):
```lua
RegisterCommand('t_log', function(source, args, rawCommand)
lib.logger(-1, 'LogTest', 'Test 123', 'test123:test123', 'rpname:Lena Meier', 'job:police')
end, true)
```
(before)
(after my changes)
I tried the following:
```lua
RegisterCommand('t_log', function(source, args, rawCommand)
lib.logger(-1, 'LogTest', 'Test 123', { rpname = "Lena Meier", job = "police" })
end, true)
```
Which ended up in this:
Probably this need some more rework, i think submitting the meta data in this format `key:value` is inconvenient. But this is out-of-scope for this "fix" 🗡️

fix(imports/logger): Loki not indexing varargs 

---

imports/table/shared.lua

Adds an optional parameter `addDuplicateNumbers` which defaults to `true` in order not to break existing behaviour.
When set to `false`, override the number keys instead.

feat(table/merge): add option to replace duplicate number keys

---

imports/timer/shared.lua

this fixes an issue that caused timers to not be able to be paused properly.
also cleans up the start method a bit
[discord support thread](https://discord.com/channels/813030955598086174/1245968051971559466)

fix for timer start method accessing private variable out of scope

---

imports/print/shared.lua

adds an exception handler to the json.encode options so that the parser prints the name of the function or the reason it couldn't parse a key instead of crashing out.
Example before:
```
SCRIPT ERROR: type 'function' is not supported by JSON
[       script:test] 
[       script:test] > libPrint (@ox_lib/imports/print/server.lua:33)
[       script:test] > info (@ox_lib/imports/print/server.lua:42)
[       script:test] > ref (@test/server/test.lua:27)
```
After:
```
script:test] [test] [INFO] {
[       script:test]     "number": 30,
[       script:test]     "string": "Los Angeles",
[       script:test]     "fthis": "function: 0000020E8ABDD3F0"
[       script:test] }
```
Optionally returning `nil` instead of `reason` would still throw an error, while allowing objects with functions on them …

prevent errors in the json encode process

---

imports/addCommand/server.lua
package/server/resource/addCommand/index.ts

Whenever you have a command that has a text type at the end where you want to catch all text from that argument and on, only the first word will be assigned to that argument and the rest ends up all in an array which makes for a mixed table. With longString it catches those extras if the argument is at the end of the given params.
For example
`/test test1 test2`
Before only `test1` would be shown.
After, all text will be shown.
*I haven't tested this yet but ChatGPT said it will work fine*

feat(addCommand): longString

---

imports/requestModel/client.lua

`IsModelInCdimage` doesn't trigger a request to load the model. This moves the check condition to trigger the correct error and restores the `RequestModel` in the streamingRequest.

fix(streaming): use RequestModel and IsModelInCdimage

---

imports/__addCommand/server.lua
imports/addCommand/server.lua

Removed the `source` as the first parameter, as the actual `source` value is set globally by fivem on event trigger.
Somehow this worked till one of the recent server builds, as the first parameter should have been the `oldID` (which is given to the user temporarily while connecting to a server and downloading the resources).
Without this change the suggestions aren't correctly send to the client and would not show up anymore.
_Tested on server build 8552, with and without the chat as a system-resource._

fix(addCommand): send chat suggestions to correct source

---

package/client/resource/interface/input.ts

fix input dialog options getting discarded in transit (this issue only affects the ts/js package for ox_lib)
- also fixes an issue in ox_core, specifically character creation, noticed you could click cancel, and be left sitting floating in the air. (tested)

fix input dialog options getting discarded in transit

---

package/server/resource/addCommand/index.ts

Prevents console warning: `Warning: [natives] TRIGGER_CLIENT_EVENT_INTERNAL: client 1 is not the same as the target 65536. This happens when the oldId from the playerJoining event is used. Use source instead.`

Remove source param from playerJoining event in js package

---

imports/table/shared.lua

Function Refactor: 
- contains
- table_matches
- table_merge

refactor and improve performance of table functions

---

imports/dui/client.lua
package/client/resource/dui/index.ts
package/client/resource/index.ts

It's really simple to create new dui and don't have to handle for resource stop etc
```lua
local dui = lib.dui:new({
url = ("nui://%s/web/index.html"):format(cache.resource), 
width = 1920, 
height = 1080,
debug = true
})
-- Change url
dui:setUrl("https://google.com")
-- Send a message
dui:sendMessage({
action = "play",
value = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
})
-- Destroy
dui:remove()
```
It's just a utility, all texture replace etc need to be handle by other scripts

feat(client/dui): implement dui handling

---

package/client/resource/interface/notify.ts

Since [interface/notify.lua](https://github.com/overextended/ox_lib/blob/master/resource/interface/client/notify.lua) has the sound variable, typescript should aswell.

feat(notify): add sound

---

resource/cache/client.lua

With this change, seat cache event listeners will be triggered all the time when the player's vehicle changes. This is useful in scenarios where the player doesn't exit the vehicle, but we switch their vehicle and warp them into the same seat index, and we want to listen to the seat event to perform specific actions. Previously, seat listeners were not being triggered because the cached seat value stayed the same.

tweak(resource/cache): update seat cache on vehicle change

---

resource/interface/client/progress.lua

- Fixes the "playEnter" arg for TaskStartScenarioInPlace animations in progress bar 
Previously, anim.playEnter would be forced to true even if the value being passed in was set to false. Now, playEnter will default to true if no value is given, otherwise it will be set to the correct boolean value.

fix(progress): playEnter arg for scenarios in progress bar

---

imports/cron/server.lua

This PR addresses two key issues with the cron implementation:
1. Fixed unintentional duplicate executions by:
- Adding lastRun timestamp tracking for each task
- Adding a 60-second cooldown check between executions
- Adding debug logging for prevented duplicates
2. Enhanced type safety and validation:
- Added proper type annotations for special cron expressions (like 'L' for last day)
- Added support for named day/month formats (mon-fri, jan,dec)
- Improved validation for ranges and step values
- Enhanced error messages for invalid expressions

fix(cron): prevent duplicate executions and enhance type safety

---

resource/interface/client/menu.lua

Opening an empty menu always leads to an error and the nui code breaking. This should prevent most cases (as there can still be people that send empty tables in the options).

fix(resource/menu): prevent opening empty menu

---

imports/marker/client.lua

Due to the way boolean values were being assigned, faceCamera would always evaluate to true because of its default value. This change fixes the logical error and ensures boolean properties are properly set.

fix(marker): logical error when setting faceCamera

---

imports/cron/server.lua

weekdayMap is written according to cron standards, getTimeUnit(self.weekday, 'wday') from the expression “‘0 12 * * * mon’” returns 8 and the cronjob was not running.

fix(cron): matching weekdayMap values with os.date wday values

---

resource/vehicleProperties/client.lua

For some reason these two properties were combined when they're not the same, this causes a bug where it would apply a livery you didn't select to be added when the vehicle has both modkit and regular liveries.

fix(resource/vehicleProperties): Fix a bug with liveries

---

resource/vehicleProperties/client.lua

Paint type appears to be overridden / ignored depending on what value is passed in for color. By passing in the default `0`, paint type should be respected once the custom rgb is applied.
Resolves #598

fix(client/vehicleproperties): Reset colors to 0 when changing painttype

---

imports/scaleform/client.lua

This add a scaleform class for a better management and usage of scaleforms.
At first it was a PR from Mycroft-Studios intended for qbx_core, but after discussions with the team we felt that this code would fit better in ox_lib so chatty asked for someone to create a PR.

Scaleform class

---

imports/getRelativeCoords/shared.lua

Added the `lib.getRelativeCoords` function, which is useful for obtaining relative coordinates on the server-side, as [GetOffsetFromCoordAndHeadingInWorldCoords](https://docs.fivem.net/natives/?_0x163E252DE035A133) native is only available on the client-side.

feat(relativeCoords): add lib.getRelativeCoords function

---

imports/getRelativeCoords/shared.lua

Allow passing a full rotation (vector3) to get the relative coords.
Usefull if the entity is rotated on other axis than just vertical.
This prevent to use a vector4 as first arg though.

refactor(relativeCoords): allow passing full rotation

---

package/client/resource/interface/input.ts

`TextAreaProps` was not referenced by `RowInput`. When using type `textarea` on `inputDialog()`, it would return the following error
`Type '"textarea"' is not assignable to type '"number" | "input" | "checkbox" | "select" | "multi-select" | "slider" | "color" | "date" | "date-range" | "time"'`

fix(types): add TextAreaProps to RowInput

---

imports/zones/client.lua

Reverse the order in which we iterate through `exitingZones` to prevent issues with the index shifting.
Fixes #712

fix(client/zones): fix nil error when multiple zones are removes at once

---

imports/zones/client.lua

This PR fixes an error that occurs when there are no duplicate z-values during poly zone creation, while keeping the existing implementation.
An alternative solution to #716

fix(zones): Fix error that occurs when there are no duplicate z-coords

---

imports/print/shared.lua

add convar change listener to print module, This would allow to set their convar at their runtime and see information without restarting resource.

feat(print): add convar change listener

---

imports/zones/shared.lua

Teleporting away from a zone you're currently in no longer triggers the onExit event with the recent grid updates. This restores that functionality.

restore onExit feature to distant zones

---

package/client/resource/callback/index.ts
package/server/resource/callback/index.ts

In the current version, ox_lib's callbacks registered via JS package are broken.
Cause:
The eventName is being mutated before calling exports.ox_lib.setValidCallback(eventName, true) which causes all callback requests to fail.
This pull request resolves #740. 
This commit reverts commit 87818b3710e465f85991fb41a1611304995dd0d3.

fix(package/callback): fix broken js callbacks

---

init.lua

This PR fixes an issue where once a Interval is cleared the CB is called twice.
Repro:

fix: check interval before calling a cb

---

package/client/resource/callback/index.ts
package/server/resource/callback/index.ts

This PR fixes a small but important issue where `resolve(args)` was passing the entire `args` array as a single element, resulting in nested arrays.
```ts
resolve(args); // args = [1, 2] → resolves as [[1, 2]]
```
```ts
resolve(...args); // args = [1, 2] → resolves as 1, 2
```
- It changes the way how it worked before v3.30.0 and breaks javascript resources that use callbacks

fix(callback/js): prevent args from being wrapped in an array when resolving the promise
