README.md

**Pull Request Description**
Readme for the intervals for ease of understand. (Credits to @thelindat) for the example code.
**Pull Request Checklist**:

Intervals Readme update

---

resource/vehicleProperties/client.lua

https://docs.fivem.net/natives/?_0x3DFF319A831E0CDB

GetVehicleXenonLightsColour -> GetVehicleXenonLightsColor

---

web/src/features/dialog/InputDialog.tsx

Added password option to text input with toggleable show state.

feat(web/dialog): Add password option to input

---

locales/al.json
locales/cr.json
locales/hu.json
locales/it.json
locales/nl.json
locales/si.json

Added multiple locales to ox_lib

feat(locales): Added locales

---

resource/interface/client/alert.lua

Allow the alert dialog to be called from server.

Add event ox_lib:alert

---

locales/es.json

spanish locales have been added

add es locales

---

imports/addCommand/server.lua

* Add ability to pass in a list of groups that can utilize the command being added

feat(addCommand): Allow multiple groups

---

web/src/features/dialog/InputDialog.tsx
web/src/features/dialog/components/slider.tsx
web/src/interfaces/dialog.ts

feat(web/dialog): Add slider input

---

imports/getClosestVehicle/client.lua
imports/getNearbyVehicles/client.lua

Definitely would find these useful, but am curious if it would be worthwhile to find a more generic way to handle getters such as these and the player equivalents.  It may be too much of a headache to be worth the generalization of the functions though.

feat(imports): getClosestVehicle and getNearbyVehicles

---

resource/interface/client/menu.lua
web/src/features/menu/list/index.tsx

* Allows a user to pass in a start index to have pre-selected when a menu is opening
* Cleaned up whitespace inconsistencies in menu.lua

feat(menu): Add option to open menu with specified item index selected

---

imports/logger/server.lua

Instead of using DataDog, due to pricing and other limitations I like to use Grafana Loki, I've added a compatibility patch for that within the logger import.
I had to do a hacky trick with the timestamp as Loki expects a nanosecond timestamp.

feat  (logger): add loki compatibility.

---

package/client/resource/interface/context.ts
resource/interface/client/context.lua
web/src/features/menu/context/ContextMenu.tsx
web/src/features/menu/context/Item.tsx

feat(interface/context): back button pressed

---

resource/cache/client.lua

feat(resource/cache): current weapon

---

locales/he.json
locales/ru.json

Fix Russian `cancel` string.
Add Hebrew.

feat(locales): update Russian & add Hebrew

---

web/src/features/menu/context/ContextMenu.tsx
web/src/features/menu/context/Item.tsx
web/src/features/notifications/NotificationWrapper.tsx

Added markdown support for context menu titles, item titles/descriptions, and notification wrapper description.

feat(interface): Markdown wrapper, notify/context

---

locales/id.json

Add id locales

---

imports/points/client.lua

Sometimes it happen so just in case

🐛 fix nearby error when index was remove

---

resource/interface/client/alert.lua

Fix alert lost focus after open 1 time

Fix alert lost focus

---

locales/zh-cn.json

Added Chinese Simplified language files.

Added Chinese Simplified language files

---

imports/getClosestObject/client.lua
imports/getNearbyObjects/client.lua
imports/getNearbyPlayers/client.lua
imports/getNearbyVehicles/client.lua

Also fixed the return params types for players and vehicles imports

feat(imports): getNearbyObjects and getClosestObject

---

package/client/resource/interface/context.ts
resource/interface/client/context.lua
web/src/features/menu/context/components/ContextButton.tsx

does what it says. Adds two new things to context options for capturing mouse enter and mouse leave events on the button.

feat(web/context): mouse enter and mouse leave events

---

web/package.json
web/pnpm-lock.yaml

Test related packages removed, do not seem to be used.
Moved all types packages to dev deps.
package name 'web' -> 'ox_lib'.

chore(web): renamed web to ox_lib and removed unused packages

---

imports/disableControls/client.lua

Missing lua typings for lib.disableControls

refactor(imports): add missing lua typings

---

resource/interface/client/menu.lua

Fix cursor being shown in menu.

Fix cursor being shown in menu.

---

locales/pt-br.json

feat(locales): Portuguese language

---

imports/getNearbyPeds/client.lua

Gets all peds that aren't players within distance

feat: getNearbyPeds

---

imports/cron/server.lua
imports/getNearbyObjects/client.lua
imports/math/shared.lua
imports/table/shared.lua
package/client/resource/interface/radial.ts
package/client/resource/streaming/index.ts
resource/interface/client/context.lua
resource/interface/client/menu.lua
resource/interface/client/notify.lua
resource/vehicleProperties/client.lua

- Add in missing js functions
- getCurrentRadialId
- requestScaleformMove
- Change up math.tohex to maintain lowercase `0x` prefix
- Add missing fields
- Removed extra whitespaces

chore: Various fix-ups from docs clean-up

---

resource/interface/client/radial.lua

fixes https://github.com/overextended/ox_lib/issues/380

fix(resource/radial): Fix RadialItem type

---

fxmanifest.lua
package/client/resource/interface/skillcheck.ts
resource/interface/client/skillcheck.lua
web/src/features/skillcheck/index.tsx

- (FEAT) Added feature to check is any active skillcheck

- (FEAT) Added feature to cancel skillcheck

---

imports/zones/client.lua

Not sure why it didn't work with vector, but it works with perfectly with table.
I'm not sure if this will be a good solution, so it would be great if you investigated the situation on your own when you have some free time.

Zone debug fix

---

web/src/features/dialog/components/fields/number.tsx
web/src/typings/dialog.ts

Added a missing property for NumberInput.

Add step property to NumberInput.

---

imports/addKeybind/client.lua

Small refactor, it should not break any existing code.
Added Secondary Key and optional Secondary Mapper.

feat(imports/addKeybind): Secondary Key

---

imports/locale/shared.lua

Allow's to nest, group locales
Usage
```locale('notifcations.something_went_wrong')```

feature (imports/locale): Read nested locales

---

imports/marker/client.lua

Example:
```lua
local marker = lib.marker.new({
type = MarkerTypes.ChevronUpx1,            -- or 52,
coords = vector3(0, 0, 0),
color = { r = 255, g = 0, b = 0, a = 255 }, -- optional
direction = vector3(0, 0, 0),              -- optional
rotation = vector3(0, 0, 0)                -- optional,
})
Citizen.CreateThread(function()
while true do
marker:draw()
Citizen.Wait(1)
end
end)
```

feature: markers

---

resource/interface/client/input.lua

fix(interface/client): clearable lua type

---

locales/cs.json

Changed some phrases so they sound more natural.

fix(locales/cs): more natural phrases

---

package/client/resource/interface/textui.ts
resource/interface/client/textui.lua
web/src/features/textui/TextUI.tsx
web/src/typings/textui.ts

Documentation Pull Request [#173](https://github.com/overextended/overextended.github.io/pull/173).

Added Bottom Centered - TextUI

---

web/src/features/skillcheck/indicator.tsx

This simple solution for detecting a cyrillic keys and convert it to right way

fix bug with wrong detection keys on cyrillic

---

locales/al.json
locales/ar.json
locales/cs.json
locales/da.json
locales/de.json
locales/en.json
locales/es.json
locales/et.json
locales/fi.json
locales/fr.json
locales/he.json
locales/hr.json
locales/hu.json
locales/id.json
locales/it.json
locales/lt.json
locales/nl.json
locales/no.json
locales/pl.json
locales/pt-br.json
locales/ru.json
locales/sk.json
locales/sl.json
locales/sv.json
locales/th.json
locales/tr.json
locales/zh-cn.json
locales/zh-tw.json
resource/interface/client/progress.lua
resource/interface/client/radial.lua

Added locale entries for the default keybind labels.

feat(interface): add locales for progress and radial menu

---

imports/marker/client.lua

add BobUpAndDown, FaceCamera, Rotate, Texture for markers

feat(class): add marker options

---

resource/interface/client/progress.lua

Changed props spawning from networked on client to just spawn non networked on clients using statebag

fix(progress/client): sync props with statebags

---

imports/getClosestObject/shared.lua
imports/getClosestPed/shared.lua
imports/getClosestPlayer/client.lua
imports/getClosestVehicle/shared.lua

Marked params that should be optional as optional.

chore(types): optional params in getClosest*

---

imports/array/shared.lua

Array:findIndex is exactly the same as Array:find

fix(array/shared) Fix Array:findIndex

---

locales/cs.json

Translated missing parts in cs.json

chore(locale): update cs.json

---

imports/raycast/client.lua

no more jitter while fpp
https://streamable.com/xe967g
[solution](https://forum.cfx.re/t/help-get-coords-where-the-player-is-looking/2766376/4?u=masnana)

feat(client/raycast): use native (GetGameplayCamRot)

---

locales/da.json
locales/de.json
locales/es.json
locales/fi.json
locales/fr.json
locales/it.json

Easydomii locales

---

imports/math/shared.lua

- Handles whole numbers and decimal places

feat(math): Add math.round function

---

imports/addCommand/server.lua

fix(addCommand): longString - empty message

---

package/client/resource/interface/menu.ts

TypeScript typing is not correct for event on check
As a result, we never get the expected result

Fix menu check

---

imports/addKeybind/client.lua

This pr adds `isPressed` states to keybinds.

feat(keybinds): added isPressed state for keybinds

---

locales/zh-cn.json
locales/zh-tw.json

- Update zh-cn translations
- Fix missing translations in zh-tw files

feat(locales): Update zh-cn and zh-tw translations

---

locales/pt-br.json

Update some locale string that were outdated and in English.

chore(locales): update pt-br.json

---

imports/cron/server.lua

This pull request supersedes [#705](https://github.com/overextended/ox_lib/pull/705), providing an alternative implementation.

feat(cron): add maxDelay property to control task execution delay

---

imports/table/shared.lua

I found it useful to create a function to randomly shuffle a table, so I created it. 
Example of use:
tbl = {1, 2, 3, 4, 5}
lib.table.shuffle(tbl)
Table is now mixed

add(imports/table): Added a table.shuffle function to shuffle a table.

---

imports/zones/shared.lua

This PR fixes few incorrect types for zone properties.

fix(zones): correct zone data types

---

locales/de.json

Missing german translation from ui.settings.notification_position.
Was in english before.

Update german translations - de.json
